export * from './acervos-routing.module'
export * from './acervos.component'
export * from './acervos.module'
export * from './acervo-detalhe'
export * from './acervo-editar'
export * from './acervo-lista'
export * from './acervo-novo'